name: Recordatorio Periodo

on:
  schedule:
    - cron: '0 13 * * 0,2,5'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Telegram
        run: |
          mensaje=$'Tienes que hacer Periodo \n\n\nPeriodo de Ningun\n\n+1 Esqueleto arquero basico'
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=$mensaje"
